CREATE TABLE smat.Empregadores (
       empregador           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       ramoAtividade        int NOT NULL,
       estado               char(5) NOT NULL,
       municipio            int NOT NULL,
       TipoEmpregador       int NOT NULL,
       razaoSocial          varchar(80) NOT NULL,
       documento            varchar(25) NULL,
       numero               int NOT NULL,
       rua                  varchar(80) NOT NULL,
       bairro               varchar(60) NOT NULL,
       cep                  char(9) NOT NULL,
       complemento          varchar(30) NULL
);