INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES ( 1,null,'Ferramentas manuais','DESCCRIAAAAATOOOOOO');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (2,null,'Máquinas e Aparelhos','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (3,null,'Produtos químicos','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (4,1,'Ferramentas manuais motorizadas','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (5,1,'Ferramentas manuais não motorizadas','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (6,1,'Outras ferramentas manuais','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (7,2,'Máquinas de agitar, misturar','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (8,2,'Máquinas agrícolas','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (9,2,'Máquinas de cortar','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (10,3,'Metais','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (11,3,'Solventes','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (12,3,'Agrotóxicos','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (13,4,'Furadeira','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (14,4,'Lixadeira','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (15,4,'Motoserra','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (16,6,'Instrumentos médico-hospitalates','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (17,6,'Ferramenta manual inconclusiva','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (18,6,'Outros','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (19,5,'AgenteCausador 19   5','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (20,5,'AgenteCausador 20   5','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (21,5,'AgenteCausador 21   5','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (22,7,'Centrífuga','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (23,7,'Misturador','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (24,7,'Agitador','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (25,8,'Classificadora','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (26,8,'Colhedoura','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (27,8,'Trator','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (28,9,'Maçarico de mesa','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (29,9,'Guilhotina','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (30,9,'Tesoura Mecânica','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (31,10,'Cádmio','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (32,10,'Chumbo','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (33,10,'Cobre','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (34,11,'Benzeno','DESCRICAO');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (35,11,'Colas','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (36,11,'Solventes clorados','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (37,12,'Carbamato','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (38,12,'Clorofenóis','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (39,12,'Organoclorado','DESC');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (40,null,'VO','');
INSERT INTO smat.agentescausadores( agentecausador, agentecausadorpai, nome, descricao) VALUES (41,40,'PAI','');