insert into smat.locaislesao values(1,'Crânio',null);
insert into smat.locaislesao values(2,'Pescoço',null);
insert into smat.locaislesao values(3,'Tronco',null);
insert into smat.locaislesao values(4,'Membros Superiores',null);
insert into smat.locaislesao values(5,'Menbros Inferiores',null);
insert into smat.locaislesao values(6,'Cabeça',1);
insert into smat.locaislesao values(7,'Face',1);
insert into smat.locaislesao values(8,'Olhos',1);
insert into smat.locaislesao values(9,'Nariz',1);
insert into smat.locaislesao values(10,'Ouvido',1);
insert into smat.locaislesao values(11,'Córnea',1);
insert into smat.locaislesao values(12,'Couro cabeludo',1);
insert into smat.locaislesao values(13,'Região cervical',2);
insert into smat.locaislesao values(14,'Laringe',2);
insert into smat.locaislesao values(15,'Traquéia',2);
insert into smat.locaislesao values(16,'Glandula tireoide',2);
insert into smat.locaislesao values(17,'Faringe',2);
insert into smat.locaislesao values(18,'Esófago cervical',2);
insert into smat.locaislesao values(19,'Região externa do pescoço',2);
insert into smat.locaislesao values(20,'Pescoço',2);
insert into smat.locaislesao values(21,'Região dorsal, torácica',3);
insert into smat.locaislesao values(22,'Região lombar',3);
insert into smat.locaislesao values(23,'Região sacral e cóccix',3);
insert into smat.locaislesao values(24,'Costelas',3);
insert into smat.locaislesao values(25,'Esterno',3);
insert into smat.locaislesao values(26,'Bacia',3);
insert into smat.locaislesao values(27,'Nádega',3);
insert into smat.locaislesao values(28,'Vísceras',3);
insert into smat.locaislesao values(29,'Região abdominal',3);
insert into smat.locaislesao values(30,'Múltiplas localizações',3);
insert into smat.locaislesao values(31,'Ombro',4);
insert into smat.locaislesao values(32,'Braço',4);
insert into smat.locaislesao values(33,'Cotovelo',4);
insert into smat.locaislesao values(34,'Antebraço',4);
insert into smat.locaislesao values(35,'Punho',4);
insert into smat.locaislesao values(36,'Mão',4);
insert into smat.locaislesao values(37,'Dedo',4);
insert into smat.locaislesao values(38,'Múltiplas localizações',4);
insert into smat.locaislesao values(39,'Outro',4);
insert into smat.locaislesao values(40,'Quadril',5);
insert into smat.locaislesao values(41,'Coxa',5);
insert into smat.locaislesao values(42,'Joelho',5);
insert into smat.locaislesao values(43,'Perna',5);
insert into smat.locaislesao values(44,'Tornozelo',5);
insert into smat.locaislesao values(45,'Pé',5);